<a href="https://colab.research.google.com/github/itohmarina/syntax_training/blob/main/SQL%E6%96%87%E3%81%AE%E7%B7%B4%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

参考: https://qiita.com/_jinta/items/fb79f9f9b65b241e92b2

In [1]:
!pip install ipython-sql==0.3.9

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ipython-sql==0.3.9 in /usr/local/lib/python3.8/dist-packages (0.3.9)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.8/dist-packages (from ipython-sql==0.3.9) (0.2.0)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from ipython-sql==0.3.9) (1.15.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.8/dist-packages (from ipython-sql==0.3.9) (3.6.0)
Requirement already satisfied: ipython>=1.0 in /usr/local/lib/python3.8/dist-packages (from ipython-sql==0.3.9) (7.9.0)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.8/dist-packages (from ipython-sql==0.3.9) (0.4.3)
Requirement already satisfied: sqlalchemy>=0.6.7 in /usr/local/lib/python3.8/dist-packages (from ipython-sql==0.3.9) (1.4.46)
Collecting jedi>=0.10
  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 24.7 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (57.4.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (4.4.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (0.2.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (2.0.10)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (2.6.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.8/dist-packages (from ipython>=1.0->ipython-sql==0.3.9) (5.7.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.8/dist-packages (from sqlalchemy>=0.6.7->ipython-sql==0.3.9) (2.0.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prettytable->ipython-sql==0.3.9) (0.2.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from jedi>=0.10->ipython>=1.0->ipython-sql==0.3.9) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.8/dist-packages (from pexpect->ipython>=1.0->ipython-sql==0.3.9) (0.7.0)
Installing collected packages: jedi
Successfully installed jedi-0.18.2

In [2]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
!unzip chinook.zip

--2023-03-06 07:28:27--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 151.139.128.10
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|151.139.128.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.03s

2023-03-06 07:28:28 (11.1 MB/s) - ‘chinook.zip’ saved [305596/305596]

Archive:  chinook.zip
  inflating: chinook.db

In [4]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [5]:
%sql sqlite:///chinook.db

'Connected: @chinook.db'

In [6]:
%sql select name from sqlite_master where type='table';

 * sqlite:///chinook.db
Done.

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [7]:
%%sql
SELECT
  *
FROM
  albums
LIMIT 5;

 * sqlite:///chinook.db
Done.

[(1, 'For Those About To Rock We Salute You', 1),
 (2, 'Balls to the Wall', 2),
 (3, 'Restless and Wild', 2),
 (4, 'Let There Be Rock', 1),
 (5, 'Big Ones', 3)]

SELECT
  (式)
FROM
  (テーブル)
LIMIT (レコード数);

*   リスト項目
*   リスト項目

In [8]:
print(_)

+---------+---------------------------------------+----------+
| AlbumId |                 Title                 | ArtistId |
+---------+---------------------------------------+----------+
|    1    | For Those About To Rock We Salute You |    1     |
|    2    |           Balls to the Wall           |    2     |
|    3    |           Restless and Wild           |    2     |
|    4    |           Let There Be Rock           |    1     |
|    5    |                Big Ones               |    3     |
+---------+---------------------------------------+----------+

In [9]:
%%sql result <<
SELECT
  Title,
  Name
FROM
  albums
INNER JOIN artists
  ON artists.ArtistId = albums.ArtistId
LIMIT 10;

 * sqlite:///chinook.db
Done.
Returning data to local variable result

In [10]:
df = result.DataFrame()
display(df)

                                   Title                  Name
0  For Those About To Rock We Salute You                 AC/DC
1                      Balls to the Wall                Accept
2                      Restless and Wild                Accept
3                      Let There Be Rock                 AC/DC
4                               Big Ones             Aerosmith
5                     Jagged Little Pill     Alanis Morissette
6                               Facelift       Alice In Chains
7                         Warner 25 Anos  Antônio Carlos Jobim
8         Plays Metallica By Four Cellos          Apocalyptica
9                             Audioslave            Audioslave

In [11]:
!wget https://raw.githubusercontent.com/mcnakhaee/palmerpenguins/master/palmerpenguins/data/penguins.csv

--2023-03-06 07:36:42--  https://raw.githubusercontent.com/mcnakhaee/palmerpenguins/master/palmerpenguins/data/penguins.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15241 (15K) [text/plain]
Saving to: ‘penguins.csv’

penguins.csv        100%[===================>]  14.88K  --.-KB/s    in 0s

2023-03-06 07:36:42 (94.4 MB/s) - ‘penguins.csv’ saved [15241/15241]

In [12]:
import sqlite3
import pandas as pd

In [13]:
df = pd.read_csv('penguins.csv')
with sqlite3.connect('penguins.db') as conn:
  df.to_sql('palmer', con=conn)

pandas経由で、sqlite3を使ってDBを作成する。
sqlite3.connect(DB_path)でデータに接続している。DBが存在しなければ新しいDBが作成される。csvをテーブルにするにはpandasのDataFrame.to_sql(table_name, connection)を使用する。

In [14]:
%sql sqlite:///penguins.db

'Connected: @penguins.db'

In [15]:
%%sql
SELECT
  *
FROM
  palmer
WHERE
  body_mass_g > 3799
LIMIT 3;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (7, 'Adelie', 'Torgersen', 39.2, 19.6, 195.0, 4675.0, 'male', 2007),
 (9, 'Adelie', 'Torgersen', 42.0, 20.2, 190.0, 4250.0, None, 2007)]

In [18]:
%%sql
SELECT *
FROM palmer
LIMIT 3;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(0, 'Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'male', 2007),
 (1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (2, 'Adelie', 'Torgersen', 40.3, 18.0, 195.0, 3250.0, 'female', 2007)]

In [20]:
%%sql
SELECT bill_length_mm, species, island
FROM palmer
LIMIT 4;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(39.1, 'Adelie', 'Torgersen'),
 (39.5, 'Adelie', 'Torgersen'),
 (40.3, 'Adelie', 'Torgersen'),
 (None, 'Adelie', 'Torgersen')]

In [23]:
%%sql
SELECT *
FROM palmer
WHERE species = 'Adelie' ;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(0, 'Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'male', 2007),
 (1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (2, 'Adelie', 'Torgersen', 40.3, 18.0, 195.0, 3250.0, 'female', 2007),
 (3, 'Adelie', 'Torgersen', None, None, None, None, None, 2007),
 (4, 'Adelie', 'Torgersen', 36.7, 19.3, 193.0, 3450.0, 'female', 2007),
 (5, 'Adelie', 'Torgersen', 39.3, 20.6, 190.0, 3650.0, 'male', 2007),
 (6, 'Adelie', 'Torgersen', 38.9, 17.8, 181.0, 3625.0, 'female', 2007),
 (7, 'Adelie', 'Torgersen', 39.2, 19.6, 195.0, 4675.0, 'male', 2007),
 (8, 'Adelie', 'Torgersen', 34.1, 18.1, 193.0, 3475.0, None, 2007),
 (9, 'Adelie', 'Torgersen', 42.0, 20.2, 190.0, 4250.0, None, 2007),
 (10, 'Adelie', 'Torgersen', 37.8, 17.1, 186.0, 3300.0, None, 2007),
 (11, 'Adelie', 'Torgersen', 37.8, 17.3, 180.0, 3700.0, None, 2007),
 (12, 'Adelie', 'Torgersen', 41.1, 17.6, 182.0, 3200.0, 'female', 2007),
 (13, 'Adelie', 'Torgersen', 38.6, 21.2, 191.0, 3800.0, 'male', 2007),
 (14, 'Adelie', 'Torgersen', 34.6, 21.1, 198.0, 4400.0, 'male', 2007),
 (15, 'Adelie', 'Torgersen', 36.6, 17.8, 185.0, 3700.0, 'female', 2007),
 (16, 'Adelie', 'Torgersen', 38.7, 19.0, 195.0, 3450.0, 'female', 2007),
 (17, 'Adelie', 'Torgersen', 42.5, 20.7, 197.0, 4500.0, 'male', 2007),
 (18, 'Adelie', 'Torgersen', 34.4, 18.4, 184.0, 3325.0, 'female', 2007),
 (19, 'Adelie', 'Torgersen', 46.0, 21.5, 194.0, 4200.0, 'male', 2007),
 (20, 'Adelie', 'Biscoe', 37.8, 18.3, 174.0, 3400.0, 'female', 2007),
 (21, 'Adelie', 'Biscoe', 37.7, 18.7, 180.0, 3600.0, 'male', 2007),
 (22, 'Adelie', 'Biscoe', 35.9, 19.2, 189.0, 3800.0, 'female', 2007),
 (23, 'Adelie', 'Biscoe', 38.2, 18.1, 185.0, 3950.0, 'male', 2007),
 (24, 'Adelie', 'Biscoe', 38.8, 17.2, 180.0, 3800.0, 'male', 2007),
 (25, 'Adelie', 'Biscoe', 35.3, 18.9, 187.0, 3800.0, 'female', 2007),
 (26, 'Adelie', 'Biscoe', 40.6, 18.6, 183.0, 3550.0, 'male', 2007),
 (27, 'Adelie', 'Biscoe', 40.5, 17.9, 187.0, 3200.0, 'female', 2007),
 (28, 'Adelie', 'Biscoe', 37.9, 18.6, 172.0, 3150.0, 'female', 2007),
 (29, 'Adelie', 'Biscoe', 40.5, 18.9, 180.0, 3950.0, 'male', 2007),
 (30, 'Adelie', 'Dream', 39.5, 16.7, 178.0, 3250.0, 'female', 2007),
 (31, 'Adelie', 'Dream', 37.2, 18.1, 178.0, 3900.0, 'male', 2007),
 (32, 'Adelie', 'Dream', 39.5, 17.8, 188.0, 3300.0, 'female', 2007),
 (33, 'Adelie', 'Dream', 40.9, 18.9, 184.0, 3900.0, 'male', 2007),
 (34, 'Adelie', 'Dream', 36.4, 17.0, 195.0, 3325.0, 'female', 2007),
 (35, 'Adelie', 'Dream', 39.2, 21.1, 196.0, 4150.0, 'male', 2007),
 (36, 'Adelie', 'Dream', 38.8, 20.0, 190.0, 3950.0, 'male', 2007),
 (37, 'Adelie', 'Dream', 42.2, 18.5, 180.0, 3550.0, 'female', 2007),
 (38, 'Adelie', 'Dream', 37.6, 19.3, 181.0, 3300.0, 'female', 2007),
 (39, 'Adelie', 'Dream', 39.8, 19.1, 184.0, 4650.0, 'male', 2007),
 (40, 'Adelie', 'Dream', 36.5, 18.0, 182.0, 3150.0, 'female', 2007),
 (41, 'Adelie', 'Dream', 40.8, 18.4, 195.0, 3900.0, 'male', 2007),
 (42, 'Adelie', 'Dream', 36.0, 18.5, 186.0, 3100.0, 'female', 2007),
 (43, 'Adelie', 'Dream', 44.1, 19.7, 196.0, 4400.0, 'male', 2007),
 (44, 'Adelie', 'Dream', 37.0, 16.9, 185.0, 3000.0, 'female', 2007),
 (45, 'Adelie', 'Dream', 39.6, 18.8, 190.0, 4600.0, 'male', 2007),
 (46, 'Adelie', 'Dream', 41.1, 19.0, 182.0, 3425.0, 'male', 2007),
 (47, 'Adelie', 'Dream', 37.5, 18.9, 179.0, 2975.0, None, 2007),
 (48, 'Adelie', 'Dream', 36.0, 17.9, 190.0, 3450.0, 'female', 2007),
 (49, 'Adelie', 'Dream', 42.3, 21.2, 191.0, 4150.0, 'male', 2007),
 (50, 'Adelie', 'Biscoe', 39.6, 17.7, 186.0, 3500.0, 'female', 2008),
 (51, 'Adelie', 'Biscoe', 40.1, 18.9, 188.0, 4300.0, 'male', 2008),
 (52, 'Adelie', 'Biscoe', 35.0, 17.9, 190.0, 3450.0, 'female', 2008),
 (53, 'Adelie', 'Biscoe', 42.0, 19.5, 200.0, 4050.0, 'male', 2008),
 (54, 'Adelie', 'Biscoe', 34.5, 18.1, 187.0, 2900.0, 'female', 2008),
 (55, 'Adelie', 'Biscoe', 41.4, 18.6, 191.0, 3700.0, 'male', 2008),
 (56, 'Adelie', 'Biscoe', 39.0, 17.5, 186.0, 3550.0, 'female', 2008),
 (57, 'Adelie', 'Biscoe', 40.6, 18.8, 193.0, 3800.0, 'male', 2008),
 (58, 'Adelie', 'Biscoe', 36.5, 16.6, 181.0, 2850.0, 'female', 2008),
 (59, 'Adelie', 'Biscoe', 37.6, 19.1, 194.0, 3750.0, 'male', 2008),
 (60, 'Adelie', 'Biscoe', 35.7, 16.9, 185.0, 3150.0, 'female', 2008),
 (61, 'Adelie', 'Biscoe', 41.3, 21.1, 195.0, 4400.0, 'male', 2008),
 (62, 'Adelie', 'Biscoe', 37.6, 17.0, 185.0, 3600.0, 'female', 2008),
 (63, 'Adelie', 'Biscoe', 41.1, 18.2, 192.0, 4050.0, 'male', 2008),
 (64, 'Adelie', 'Biscoe', 36.4, 17.1, 184.0, 2850.0, 'female', 2008),
 (65, 'Adelie', 'Biscoe', 41.6, 18.0, 192.0, 3950.0, 'male', 2008),
 (66, 'Adelie', 'Biscoe', 35.5, 16.2, 195.0, 3350.0, 'female', 2008),
 (67, 'Adelie', 'Biscoe', 41.1, 19.1, 188.0, 4100.0, 'male', 2008),
 (68, 'Adelie', 'Torgersen', 35.9, 16.6, 190.0, 3050.0, 'female', 2008),
 (69, 'Adelie', 'Torgersen', 41.8, 19.4, 198.0, 4450.0, 'male', 2008),
 (70, 'Adelie', 'Torgersen', 33.5, 19.0, 190.0, 3600.0, 'female', 2008),
 (71, 'Adelie', 'Torgersen', 39.7, 18.4, 190.0, 3900.0, 'male', 2008),
 (72, 'Adelie', 'Torgersen', 39.6, 17.2, 196.0, 3550.0, 'female', 2008),
 (73, 'Adelie', 'Torgersen', 45.8, 18.9, 197.0, 4150.0, 'male', 2008),
 (74, 'Adelie', 'Torgersen', 35.5, 17.5, 190.0, 3700.0, 'female', 2008),
 (75, 'Adelie', 'Torgersen', 42.8, 18.5, 195.0, 4250.0, 'male', 2008),
 (76, 'Adelie', 'Torgersen', 40.9, 16.8, 191.0, 3700.0, 'female', 2008),
 (77, 'Adelie', 'Torgersen', 37.2, 19.4, 184.0, 3900.0, 'male', 2008),
 (78, 'Adelie', 'Torgersen', 36.2, 16.1, 187.0, 3550.0, 'female', 2008),
 (79, 'Adelie', 'Torgersen', 42.1, 19.1, 195.0, 4000.0, 'male', 2008),
 (80, 'Adelie', 'Torgersen', 34.6, 17.2, 189.0, 3200.0, 'female', 2008),
 (81, 'Adelie', 'Torgersen', 42.9, 17.6, 196.0, 4700.0, 'male', 2008),
 (82, 'Adelie', 'Torgersen', 36.7, 18.8, 187.0, 3800.0, 'female', 2008),
 (83, 'Adelie', 'Torgersen', 35.1, 19.4, 193.0, 4200.0, 'male', 2008),
 (84, 'Adelie', 'Dream', 37.3, 17.8, 191.0, 3350.0, 'female', 2008),
 (85, 'Adelie', 'Dream', 41.3, 20.3, 194.0, 3550.0, 'male', 2008),
 (86, 'Adelie', 'Dream', 36.3, 19.5, 190.0, 3800.0, 'male', 2008),
 (87, 'Adelie', 'Dream', 36.9, 18.6, 189.0, 3500.0, 'female', 2008),
 (88, 'Adelie', 'Dream', 38.3, 19.2, 189.0, 3950.0, 'male', 2008),
 (89, 'Adelie', 'Dream', 38.9, 18.8, 190.0, 3600.0, 'female', 2008),
 (90, 'Adelie', 'Dream', 35.7, 18.0, 202.0, 3550.0, 'female', 2008),
 (91, 'Adelie', 'Dream', 41.1, 18.1, 205.0, 4300.0, 'male', 2008),
 (92, 'Adelie', 'Dream', 34.0, 17.1, 185.0, 3400.0, 'female', 2008),
 (93, 'Adelie', 'Dream', 39.6, 18.1, 186.0, 4450.0, 'male', 2008),
 (94, 'Adelie', 'Dream', 36.2, 17.3, 187.0, 3300.0, 'female', 2008),
 (95, 'Adelie', 'Dream', 40.8, 18.9, 208.0, 4300.0, 'male', 2008),
 (96, 'Adelie', 'Dream', 38.1, 18.6, 190.0, 3700.0, 'female', 2008),
 (97, 'Adelie', 'Dream', 40.3, 18.5, 196.0, 4350.0, 'male', 2008),
 (98, 'Adelie', 'Dream', 33.1, 16.1, 178.0, 2900.0, 'female', 2008),
 (99, 'Adelie', 'Dream', 43.2, 18.5, 192.0, 4100.0, 'male', 2008),
 (100, 'Adelie', 'Biscoe', 35.0, 17.9, 192.0, 3725.0, 'female', 2009),
 (101, 'Adelie', 'Biscoe', 41.0, 20.0, 203.0, 4725.0, 'male', 2009),
 (102, 'Adelie', 'Biscoe', 37.7, 16.0, 183.0, 3075.0, 'female', 2009),
 (103, 'Adelie', 'Biscoe', 37.8, 20.0, 190.0, 4250.0, 'male', 2009),
 (104, 'Adelie', 'Biscoe', 37.9, 18.6, 193.0, 2925.0, 'female', 2009),
 (105, 'Adelie', 'Biscoe', 39.7, 18.9, 184.0, 3550.0, 'male', 2009),
 (106, 'Adelie', 'Biscoe', 38.6, 17.2, 199.0, 3750.0, 'female', 2009),
 (107, 'Adelie', 'Biscoe', 38.2, 20.0, 190.0, 3900.0, 'male', 2009),
 (108, 'Adelie', 'Biscoe', 38.1, 17.0, 181.0, 3175.0, 'female', 2009),
 (109, 'Adelie', 'Biscoe', 43.2, 19.0, 197.0, 4775.0, 'male', 2009),
 (110, 'Adelie', 'Biscoe', 38.1, 16.5, 198.0, 3825.0, 'female', 2009),
 (111, 'Adelie', 'Biscoe', 45.6, 20.3, 191.0, 4600.0, 'male', 2009),
 (112, 'Adelie', 'Biscoe', 39.7, 17.7, 193.0, 3200.0, 'female', 2009),
 (113, 'Adelie', 'Biscoe', 42.2, 19.5, 197.0, 4275.0, 'male', 2009),
 (114, 'Adelie', 'Biscoe', 39.6, 20.7, 191.0, 3900.0, 'female', 2009),
 (115, 'Adelie', 'Biscoe', 42.7, 18.3, 196.0, 4075.0, 'male', 2009),
 (116, 'Adelie', 'Torgersen', 38.6, 17.0, 188.0, 2900.0, 'female', 2009),
 (117, 'Adelie', 'Torgersen', 37.3, 20.5, 199.0, 3775.0, 'male', 2009),
 (118, 'Adelie', 'Torgersen', 35.7, 17.0, 189.0, 3350.0, 'female', 2009),
 (119, 'Adelie', 'Torgersen', 41.1, 18.6, 189.0, 3325.0, 'male', 2009),
 (120, 'Adelie', 'Torgersen', 36.2, 17.2, 187.0, 3150.0, 'female', 2009),
 (121, 'Adelie', 'Torgersen', 37.7, 19.8, 198.0, 3500.0, 'male', 2009),
 (122, 'Adelie', 'Torgersen', 40.2, 17.0, 176.0, 3450.0, 'female', 2009),
 (123, 'Adelie', 'Torgersen', 41.4, 18.5, 202.0, 3875.0, 'male', 2009),
 (124, 'Adelie', 'Torgersen', 35.2, 15.9, 186.0, 3050.0, 'female', 2009),
 (125, 'Adelie', 'Torgersen', 40.6, 19.0, 199.0, 4000.0, 'male', 2009),
 (126, 'Adelie', 'Torgersen', 38.8, 17.6, 191.0, 3275.0, 'female', 2009),
 (127, 'Adelie', 'Torgersen', 41.5, 18.3, 195.0, 4300.0, 'male', 2009),
 (128, 'Adelie', 'Torgersen', 39.0, 17.1, 191.0, 3050.0, 'female', 2009),
 (129, 'Adelie', 'Torgersen', 44.1, 18.0, 210.0, 4000.0, 'male', 2009),
 (130, 'Adelie', 'Torgersen', 38.5, 17.9, 190.0, 3325.0, 'female', 2009),
 (131, 'Adelie', 'Torgersen', 43.1, 19.2, 197.0, 3500.0, 'male', 2009),
 (132, 'Adelie', 'Dream', 36.8, 18.5, 193.0, 3500.0, 'female', 2009),
 (133, 'Adelie', 'Dream', 37.5, 18.5, 199.0, 4475.0, 'male', 2009),
 (134, 'Adelie', 'Dream', 38.1, 17.6, 187.0, 3425.0, 'female', 2009),
 (135, 'Adelie', 'Dream', 41.1, 17.5, 190.0, 3900.0, 'male', 2009),
 (136, 'Adelie', 'Dream', 35.6, 17.5, 191.0, 3175.0, 'female', 2009),
 (137, 'Adelie', 'Dream', 40.2, 20.1, 200.0, 3975.0, 'male', 2009),
 (138, 'Adelie', 'Dream', 37.0, 16.5, 185.0, 3400.0, 'female', 2009),
 (139, 'Adelie', 'Dream', 39.7, 17.9, 193.0, 4250.0, 'male', 2009),
 (140, 'Adelie', 'Dream', 40.2, 17.1, 193.0, 3400.0, 'female', 2009),
 (141, 'Adelie', 'Dream', 40.6, 17.2, 187.0, 3475.0, 'male', 2009),
 (142, 'Adelie', 'Dream', 32.1, 15.5, 188.0, 3050.0, 'female', 2009),
 (143, 'Adelie', 'Dream', 40.7, 17.0, 190.0, 3725.0, 'male', 2009),
 (144, 'Adelie', 'Dream', 37.3, 16.8, 192.0, 3000.0, 'female', 2009),
 (145, 'Adelie', 'Dream', 39.0, 18.7, 185.0, 3650.0, 'male', 2009),
 (146, 'Adelie', 'Dream', 39.2, 18.6, 190.0, 4250.0, 'male', 2009),
 (147, 'Adelie', 'Dream', 36.6, 18.4, 184.0, 3475.0, 'female', 2009),
 (148, 'Adelie', 'Dream', 36.0, 17.8, 195.0, 3450.0, 'female', 2009),
 (149, 'Adelie', 'Dream', 37.8, 18.1, 193.0, 3750.0, 'male', 2009),
 (150, 'Adelie', 'Dream', 36.0, 17.1, 187.0, 3700.0, 'female', 2009),
 (151, 'Adelie', 'Dream', 41.5, 18.5, 201.0, 4000.0, 'male', 2009)]

In [25]:
%%sql
SELECT *
FROM palmer
WHERE bill_length_mm <= 40 ;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(0, 'Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'male', 2007),
 (1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (4, 'Adelie', 'Torgersen', 36.7, 19.3, 193.0, 3450.0, 'female', 2007),
 (5, 'Adelie', 'Torgersen', 39.3, 20.6, 190.0, 3650.0, 'male', 2007),
 (6, 'Adelie', 'Torgersen', 38.9, 17.8, 181.0, 3625.0, 'female', 2007),
 (7, 'Adelie', 'Torgersen', 39.2, 19.6, 195.0, 4675.0, 'male', 2007),
 (8, 'Adelie', 'Torgersen', 34.1, 18.1, 193.0, 3475.0, None, 2007),
 (10, 'Adelie', 'Torgersen', 37.8, 17.1, 186.0, 3300.0, None, 2007),
 (11, 'Adelie', 'Torgersen', 37.8, 17.3, 180.0, 3700.0, None, 2007),
 (13, 'Adelie', 'Torgersen', 38.6, 21.2, 191.0, 3800.0, 'male', 2007),
 (14, 'Adelie', 'Torgersen', 34.6, 21.1, 198.0, 4400.0, 'male', 2007),
 (15, 'Adelie', 'Torgersen', 36.6, 17.8, 185.0, 3700.0, 'female', 2007),
 (16, 'Adelie', 'Torgersen', 38.7, 19.0, 195.0, 3450.0, 'female', 2007),
 (18, 'Adelie', 'Torgersen', 34.4, 18.4, 184.0, 3325.0, 'female', 2007),
 (20, 'Adelie', 'Biscoe', 37.8, 18.3, 174.0, 3400.0, 'female', 2007),
 (21, 'Adelie', 'Biscoe', 37.7, 18.7, 180.0, 3600.0, 'male', 2007),
 (22, 'Adelie', 'Biscoe', 35.9, 19.2, 189.0, 3800.0, 'female', 2007),
 (23, 'Adelie', 'Biscoe', 38.2, 18.1, 185.0, 3950.0, 'male', 2007),
 (24, 'Adelie', 'Biscoe', 38.8, 17.2, 180.0, 3800.0, 'male', 2007),
 (25, 'Adelie', 'Biscoe', 35.3, 18.9, 187.0, 3800.0, 'female', 2007),
 (28, 'Adelie', 'Biscoe', 37.9, 18.6, 172.0, 3150.0, 'female', 2007),
 (30, 'Adelie', 'Dream', 39.5, 16.7, 178.0, 3250.0, 'female', 2007),
 (31, 'Adelie', 'Dream', 37.2, 18.1, 178.0, 3900.0, 'male', 2007),
 (32, 'Adelie', 'Dream', 39.5, 17.8, 188.0, 3300.0, 'female', 2007),
 (34, 'Adelie', 'Dream', 36.4, 17.0, 195.0, 3325.0, 'female', 2007),
 (35, 'Adelie', 'Dream', 39.2, 21.1, 196.0, 4150.0, 'male', 2007),
 (36, 'Adelie', 'Dream', 38.8, 20.0, 190.0, 3950.0, 'male', 2007),
 (38, 'Adelie', 'Dream', 37.6, 19.3, 181.0, 3300.0, 'female', 2007),
 (39, 'Adelie', 'Dream', 39.8, 19.1, 184.0, 4650.0, 'male', 2007),
 (40, 'Adelie', 'Dream', 36.5, 18.0, 182.0, 3150.0, 'female', 2007),
 (42, 'Adelie', 'Dream', 36.0, 18.5, 186.0, 3100.0, 'female', 2007),
 (44, 'Adelie', 'Dream', 37.0, 16.9, 185.0, 3000.0, 'female', 2007),
 (45, 'Adelie', 'Dream', 39.6, 18.8, 190.0, 4600.0, 'male', 2007),
 (47, 'Adelie', 'Dream', 37.5, 18.9, 179.0, 2975.0, None, 2007),
 (48, 'Adelie', 'Dream', 36.0, 17.9, 190.0, 3450.0, 'female', 2007),
 (50, 'Adelie', 'Biscoe', 39.6, 17.7, 186.0, 3500.0, 'female', 2008),
 (52, 'Adelie', 'Biscoe', 35.0, 17.9, 190.0, 3450.0, 'female', 2008),
 (54, 'Adelie', 'Biscoe', 34.5, 18.1, 187.0, 2900.0, 'female', 2008),
 (56, 'Adelie', 'Biscoe', 39.0, 17.5, 186.0, 3550.0, 'female', 2008),
 (58, 'Adelie', 'Biscoe', 36.5, 16.6, 181.0, 2850.0, 'female', 2008),
 (59, 'Adelie', 'Biscoe', 37.6, 19.1, 194.0, 3750.0, 'male', 2008),
 (60, 'Adelie', 'Biscoe', 35.7, 16.9, 185.0, 3150.0, 'female', 2008),
 (62, 'Adelie', 'Biscoe', 37.6, 17.0, 185.0, 3600.0, 'female', 2008),
 (64, 'Adelie', 'Biscoe', 36.4, 17.1, 184.0, 2850.0, 'female', 2008),
 (66, 'Adelie', 'Biscoe', 35.5, 16.2, 195.0, 3350.0, 'female', 2008),
 (68, 'Adelie', 'Torgersen', 35.9, 16.6, 190.0, 3050.0, 'female', 2008),
 (70, 'Adelie', 'Torgersen', 33.5, 19.0, 190.0, 3600.0, 'female', 2008),
 (71, 'Adelie', 'Torgersen', 39.7, 18.4, 190.0, 3900.0, 'male', 2008),
 (72, 'Adelie', 'Torgersen', 39.6, 17.2, 196.0, 3550.0, 'female', 2008),
 (74, 'Adelie', 'Torgersen', 35.5, 17.5, 190.0, 3700.0, 'female', 2008),
 (77, 'Adelie', 'Torgersen', 37.2, 19.4, 184.0, 3900.0, 'male', 2008),
 (78, 'Adelie', 'Torgersen', 36.2, 16.1, 187.0, 3550.0, 'female', 2008),
 (80, 'Adelie', 'Torgersen', 34.6, 17.2, 189.0, 3200.0, 'female', 2008),
 (82, 'Adelie', 'Torgersen', 36.7, 18.8, 187.0, 3800.0, 'female', 2008),
 (83, 'Adelie', 'Torgersen', 35.1, 19.4, 193.0, 4200.0, 'male', 2008),
 (84, 'Adelie', 'Dream', 37.3, 17.8, 191.0, 3350.0, 'female', 2008),
 (86, 'Adelie', 'Dream', 36.3, 19.5, 190.0, 3800.0, 'male', 2008),
 (87, 'Adelie', 'Dream', 36.9, 18.6, 189.0, 3500.0, 'female', 2008),
 (88, 'Adelie', 'Dream', 38.3, 19.2, 189.0, 3950.0, 'male', 2008),
 (89, 'Adelie', 'Dream', 38.9, 18.8, 190.0, 3600.0, 'female', 2008),
 (90, 'Adelie', 'Dream', 35.7, 18.0, 202.0, 3550.0, 'female', 2008),
 (92, 'Adelie', 'Dream', 34.0, 17.1, 185.0, 3400.0, 'female', 2008),
 (93, 'Adelie', 'Dream', 39.6, 18.1, 186.0, 4450.0, 'male', 2008),
 (94, 'Adelie', 'Dream', 36.2, 17.3, 187.0, 3300.0, 'female', 2008),
 (96, 'Adelie', 'Dream', 38.1, 18.6, 190.0, 3700.0, 'female', 2008),
 (98, 'Adelie', 'Dream', 33.1, 16.1, 178.0, 2900.0, 'female', 2008),
 (100, 'Adelie', 'Biscoe', 35.0, 17.9, 192.0, 3725.0, 'female', 2009),
 (102, 'Adelie', 'Biscoe', 37.7, 16.0, 183.0, 3075.0, 'female', 2009),
 (103, 'Adelie', 'Biscoe', 37.8, 20.0, 190.0, 4250.0, 'male', 2009),
 (104, 'Adelie', 'Biscoe', 37.9, 18.6, 193.0, 2925.0, 'female', 2009),
 (105, 'Adelie', 'Biscoe', 39.7, 18.9, 184.0, 3550.0, 'male', 2009),
 (106, 'Adelie', 'Biscoe', 38.6, 17.2, 199.0, 3750.0, 'female', 2009),
 (107, 'Adelie', 'Biscoe', 38.2, 20.0, 190.0, 3900.0, 'male', 2009),
 (108, 'Adelie', 'Biscoe', 38.1, 17.0, 181.0, 3175.0, 'female', 2009),
 (110, 'Adelie', 'Biscoe', 38.1, 16.5, 198.0, 3825.0, 'female', 2009),
 (112, 'Adelie', 'Biscoe', 39.7, 17.7, 193.0, 3200.0, 'female', 2009),
 (114, 'Adelie', 'Biscoe', 39.6, 20.7, 191.0, 3900.0, 'female', 2009),
 (116, 'Adelie', 'Torgersen', 38.6, 17.0, 188.0, 2900.0, 'female', 2009),
 (117, 'Adelie', 'Torgersen', 37.3, 20.5, 199.0, 3775.0, 'male', 2009),
 (118, 'Adelie', 'Torgersen', 35.7, 17.0, 189.0, 3350.0, 'female', 2009),
 (120, 'Adelie', 'Torgersen', 36.2, 17.2, 187.0, 3150.0, 'female', 2009),
 (121, 'Adelie', 'Torgersen', 37.7, 19.8, 198.0, 3500.0, 'male', 2009),
 (124, 'Adelie', 'Torgersen', 35.2, 15.9, 186.0, 3050.0, 'female', 2009),
 (126, 'Adelie', 'Torgersen', 38.8, 17.6, 191.0, 3275.0, 'female', 2009),
 (128, 'Adelie', 'Torgersen', 39.0, 17.1, 191.0, 3050.0, 'female', 2009),
 (130, 'Adelie', 'Torgersen', 38.5, 17.9, 190.0, 3325.0, 'female', 2009),
 (132, 'Adelie', 'Dream', 36.8, 18.5, 193.0, 3500.0, 'female', 2009),
 (133, 'Adelie', 'Dream', 37.5, 18.5, 199.0, 4475.0, 'male', 2009),
 (134, 'Adelie', 'Dream', 38.1, 17.6, 187.0, 3425.0, 'female', 2009),
 (136, 'Adelie', 'Dream', 35.6, 17.5, 191.0, 3175.0, 'female', 2009),
 (138, 'Adelie', 'Dream', 37.0, 16.5, 185.0, 3400.0, 'female', 2009),
 (139, 'Adelie', 'Dream', 39.7, 17.9, 193.0, 4250.0, 'male', 2009),
 (142, 'Adelie', 'Dream', 32.1, 15.5, 188.0, 3050.0, 'female', 2009),
 (144, 'Adelie', 'Dream', 37.3, 16.8, 192.0, 3000.0, 'female', 2009),
 (145, 'Adelie', 'Dream', 39.0, 18.7, 185.0, 3650.0, 'male', 2009),
 (146, 'Adelie', 'Dream', 39.2, 18.6, 190.0, 4250.0, 'male', 2009),
 (147, 'Adelie', 'Dream', 36.6, 18.4, 184.0, 3475.0, 'female', 2009),
 (148, 'Adelie', 'Dream', 36.0, 17.8, 195.0, 3450.0, 'female', 2009),
 (149, 'Adelie', 'Dream', 37.8, 18.1, 193.0, 3750.0, 'male', 2009),
 (150, 'Adelie', 'Dream', 36.0, 17.1, 187.0, 3700.0, 'female', 2009)]

In [27]:
%%sql
SELECT *
FROM palmer
WHERE species LIKE "%deli%";

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(0, 'Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'male', 2007),
 (1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (2, 'Adelie', 'Torgersen', 40.3, 18.0, 195.0, 3250.0, 'female', 2007),
 (3, 'Adelie', 'Torgersen', None, None, None, None, None, 2007),
 (4, 'Adelie', 'Torgersen', 36.7, 19.3, 193.0, 3450.0, 'female', 2007),
 (5, 'Adelie', 'Torgersen', 39.3, 20.6, 190.0, 3650.0, 'male', 2007),
 (6, 'Adelie', 'Torgersen', 38.9, 17.8, 181.0, 3625.0, 'female', 2007),
 (7, 'Adelie', 'Torgersen', 39.2, 19.6, 195.0, 4675.0, 'male', 2007),
 (8, 'Adelie', 'Torgersen', 34.1, 18.1, 193.0, 3475.0, None, 2007),
 (9, 'Adelie', 'Torgersen', 42.0, 20.2, 190.0, 4250.0, None, 2007),
 (10, 'Adelie', 'Torgersen', 37.8, 17.1, 186.0, 3300.0, None, 2007),
 (11, 'Adelie', 'Torgersen', 37.8, 17.3, 180.0, 3700.0, None, 2007),
 (12, 'Adelie', 'Torgersen', 41.1, 17.6, 182.0, 3200.0, 'female', 2007),
 (13, 'Adelie', 'Torgersen', 38.6, 21.2, 191.0, 3800.0, 'male', 2007),
 (14, 'Adelie', 'Torgersen', 34.6, 21.1, 198.0, 4400.0, 'male', 2007),
 (15, 'Adelie', 'Torgersen', 36.6, 17.8, 185.0, 3700.0, 'female', 2007),
 (16, 'Adelie', 'Torgersen', 38.7, 19.0, 195.0, 3450.0, 'female', 2007),
 (17, 'Adelie', 'Torgersen', 42.5, 20.7, 197.0, 4500.0, 'male', 2007),
 (18, 'Adelie', 'Torgersen', 34.4, 18.4, 184.0, 3325.0, 'female', 2007),
 (19, 'Adelie', 'Torgersen', 46.0, 21.5, 194.0, 4200.0, 'male', 2007),
 (20, 'Adelie', 'Biscoe', 37.8, 18.3, 174.0, 3400.0, 'female', 2007),
 (21, 'Adelie', 'Biscoe', 37.7, 18.7, 180.0, 3600.0, 'male', 2007),
 (22, 'Adelie', 'Biscoe', 35.9, 19.2, 189.0, 3800.0, 'female', 2007),
 (23, 'Adelie', 'Biscoe', 38.2, 18.1, 185.0, 3950.0, 'male', 2007),
 (24, 'Adelie', 'Biscoe', 38.8, 17.2, 180.0, 3800.0, 'male', 2007),
 (25, 'Adelie', 'Biscoe', 35.3, 18.9, 187.0, 3800.0, 'female', 2007),
 (26, 'Adelie', 'Biscoe', 40.6, 18.6, 183.0, 3550.0, 'male', 2007),
 (27, 'Adelie', 'Biscoe', 40.5, 17.9, 187.0, 3200.0, 'female', 2007),
 (28, 'Adelie', 'Biscoe', 37.9, 18.6, 172.0, 3150.0, 'female', 2007),
 (29, 'Adelie', 'Biscoe', 40.5, 18.9, 180.0, 3950.0, 'male', 2007),
 (30, 'Adelie', 'Dream', 39.5, 16.7, 178.0, 3250.0, 'female', 2007),
 (31, 'Adelie', 'Dream', 37.2, 18.1, 178.0, 3900.0, 'male', 2007),
 (32, 'Adelie', 'Dream', 39.5, 17.8, 188.0, 3300.0, 'female', 2007),
 (33, 'Adelie', 'Dream', 40.9, 18.9, 184.0, 3900.0, 'male', 2007),
 (34, 'Adelie', 'Dream', 36.4, 17.0, 195.0, 3325.0, 'female', 2007),
 (35, 'Adelie', 'Dream', 39.2, 21.1, 196.0, 4150.0, 'male', 2007),
 (36, 'Adelie', 'Dream', 38.8, 20.0, 190.0, 3950.0, 'male', 2007),
 (37, 'Adelie', 'Dream', 42.2, 18.5, 180.0, 3550.0, 'female', 2007),
 (38, 'Adelie', 'Dream', 37.6, 19.3, 181.0, 3300.0, 'female', 2007),
 (39, 'Adelie', 'Dream', 39.8, 19.1, 184.0, 4650.0, 'male', 2007),
 (40, 'Adelie', 'Dream', 36.5, 18.0, 182.0, 3150.0, 'female', 2007),
 (41, 'Adelie', 'Dream', 40.8, 18.4, 195.0, 3900.0, 'male', 2007),
 (42, 'Adelie', 'Dream', 36.0, 18.5, 186.0, 3100.0, 'female', 2007),
 (43, 'Adelie', 'Dream', 44.1, 19.7, 196.0, 4400.0, 'male', 2007),
 (44, 'Adelie', 'Dream', 37.0, 16.9, 185.0, 3000.0, 'female', 2007),
 (45, 'Adelie', 'Dream', 39.6, 18.8, 190.0, 4600.0, 'male', 2007),
 (46, 'Adelie', 'Dream', 41.1, 19.0, 182.0, 3425.0, 'male', 2007),
 (47, 'Adelie', 'Dream', 37.5, 18.9, 179.0, 2975.0, None, 2007),
 (48, 'Adelie', 'Dream', 36.0, 17.9, 190.0, 3450.0, 'female', 2007),
 (49, 'Adelie', 'Dream', 42.3, 21.2, 191.0, 4150.0, 'male', 2007),
 (50, 'Adelie', 'Biscoe', 39.6, 17.7, 186.0, 3500.0, 'female', 2008),
 (51, 'Adelie', 'Biscoe', 40.1, 18.9, 188.0, 4300.0, 'male', 2008),
 (52, 'Adelie', 'Biscoe', 35.0, 17.9, 190.0, 3450.0, 'female', 2008),
 (53, 'Adelie', 'Biscoe', 42.0, 19.5, 200.0, 4050.0, 'male', 2008),
 (54, 'Adelie', 'Biscoe', 34.5, 18.1, 187.0, 2900.0, 'female', 2008),
 (55, 'Adelie', 'Biscoe', 41.4, 18.6, 191.0, 3700.0, 'male', 2008),
 (56, 'Adelie', 'Biscoe', 39.0, 17.5, 186.0, 3550.0, 'female', 2008),
 (57, 'Adelie', 'Biscoe', 40.6, 18.8, 193.0, 3800.0, 'male', 2008),
 (58, 'Adelie', 'Biscoe', 36.5, 16.6, 181.0, 2850.0, 'female', 2008),
 (59, 'Adelie', 'Biscoe', 37.6, 19.1, 194.0, 3750.0, 'male', 2008),
 (60, 'Adelie', 'Biscoe', 35.7, 16.9, 185.0, 3150.0, 'female', 2008),
 (61, 'Adelie', 'Biscoe', 41.3, 21.1, 195.0, 4400.0, 'male', 2008),
 (62, 'Adelie', 'Biscoe', 37.6, 17.0, 185.0, 3600.0, 'female', 2008),
 (63, 'Adelie', 'Biscoe', 41.1, 18.2, 192.0, 4050.0, 'male', 2008),
 (64, 'Adelie', 'Biscoe', 36.4, 17.1, 184.0, 2850.0, 'female', 2008),
 (65, 'Adelie', 'Biscoe', 41.6, 18.0, 192.0, 3950.0, 'male', 2008),
 (66, 'Adelie', 'Biscoe', 35.5, 16.2, 195.0, 3350.0, 'female', 2008),
 (67, 'Adelie', 'Biscoe', 41.1, 19.1, 188.0, 4100.0, 'male', 2008),
 (68, 'Adelie', 'Torgersen', 35.9, 16.6, 190.0, 3050.0, 'female', 2008),
 (69, 'Adelie', 'Torgersen', 41.8, 19.4, 198.0, 4450.0, 'male', 2008),
 (70, 'Adelie', 'Torgersen', 33.5, 19.0, 190.0, 3600.0, 'female', 2008),
 (71, 'Adelie', 'Torgersen', 39.7, 18.4, 190.0, 3900.0, 'male', 2008),
 (72, 'Adelie', 'Torgersen', 39.6, 17.2, 196.0, 3550.0, 'female', 2008),
 (73, 'Adelie', 'Torgersen', 45.8, 18.9, 197.0, 4150.0, 'male', 2008),
 (74, 'Adelie', 'Torgersen', 35.5, 17.5, 190.0, 3700.0, 'female', 2008),
 (75, 'Adelie', 'Torgersen', 42.8, 18.5, 195.0, 4250.0, 'male', 2008),
 (76, 'Adelie', 'Torgersen', 40.9, 16.8, 191.0, 3700.0, 'female', 2008),
 (77, 'Adelie', 'Torgersen', 37.2, 19.4, 184.0, 3900.0, 'male', 2008),
 (78, 'Adelie', 'Torgersen', 36.2, 16.1, 187.0, 3550.0, 'female', 2008),
 (79, 'Adelie', 'Torgersen', 42.1, 19.1, 195.0, 4000.0, 'male', 2008),
 (80, 'Adelie', 'Torgersen', 34.6, 17.2, 189.0, 3200.0, 'female', 2008),
 (81, 'Adelie', 'Torgersen', 42.9, 17.6, 196.0, 4700.0, 'male', 2008),
 (82, 'Adelie', 'Torgersen', 36.7, 18.8, 187.0, 3800.0, 'female', 2008),
 (83, 'Adelie', 'Torgersen', 35.1, 19.4, 193.0, 4200.0, 'male', 2008),
 (84, 'Adelie', 'Dream', 37.3, 17.8, 191.0, 3350.0, 'female', 2008),
 (85, 'Adelie', 'Dream', 41.3, 20.3, 194.0, 3550.0, 'male', 2008),
 (86, 'Adelie', 'Dream', 36.3, 19.5, 190.0, 3800.0, 'male', 2008),
 (87, 'Adelie', 'Dream', 36.9, 18.6, 189.0, 3500.0, 'female', 2008),
 (88, 'Adelie', 'Dream', 38.3, 19.2, 189.0, 3950.0, 'male', 2008),
 (89, 'Adelie', 'Dream', 38.9, 18.8, 190.0, 3600.0, 'female', 2008),
 (90, 'Adelie', 'Dream', 35.7, 18.0, 202.0, 3550.0, 'female', 2008),
 (91, 'Adelie', 'Dream', 41.1, 18.1, 205.0, 4300.0, 'male', 2008),
 (92, 'Adelie', 'Dream', 34.0, 17.1, 185.0, 3400.0, 'female', 2008),
 (93, 'Adelie', 'Dream', 39.6, 18.1, 186.0, 4450.0, 'male', 2008),
 (94, 'Adelie', 'Dream', 36.2, 17.3, 187.0, 3300.0, 'female', 2008),
 (95, 'Adelie', 'Dream', 40.8, 18.9, 208.0, 4300.0, 'male', 2008),
 (96, 'Adelie', 'Dream', 38.1, 18.6, 190.0, 3700.0, 'female', 2008),
 (97, 'Adelie', 'Dream', 40.3, 18.5, 196.0, 4350.0, 'male', 2008),
 (98, 'Adelie', 'Dream', 33.1, 16.1, 178.0, 2900.0, 'female', 2008),
 (99, 'Adelie', 'Dream', 43.2, 18.5, 192.0, 4100.0, 'male', 2008),
 (100, 'Adelie', 'Biscoe', 35.0, 17.9, 192.0, 3725.0, 'female', 2009),
 (101, 'Adelie', 'Biscoe', 41.0, 20.0, 203.0, 4725.0, 'male', 2009),
 (102, 'Adelie', 'Biscoe', 37.7, 16.0, 183.0, 3075.0, 'female', 2009),
 (103, 'Adelie', 'Biscoe', 37.8, 20.0, 190.0, 4250.0, 'male', 2009),
 (104, 'Adelie', 'Biscoe', 37.9, 18.6, 193.0, 2925.0, 'female', 2009),
 (105, 'Adelie', 'Biscoe', 39.7, 18.9, 184.0, 3550.0, 'male', 2009),
 (106, 'Adelie', 'Biscoe', 38.6, 17.2, 199.0, 3750.0, 'female', 2009),
 (107, 'Adelie', 'Biscoe', 38.2, 20.0, 190.0, 3900.0, 'male', 2009),
 (108, 'Adelie', 'Biscoe', 38.1, 17.0, 181.0, 3175.0, 'female', 2009),
 (109, 'Adelie', 'Biscoe', 43.2, 19.0, 197.0, 4775.0, 'male', 2009),
 (110, 'Adelie', 'Biscoe', 38.1, 16.5, 198.0, 3825.0, 'female', 2009),
 (111, 'Adelie', 'Biscoe', 45.6, 20.3, 191.0, 4600.0, 'male', 2009),
 (112, 'Adelie', 'Biscoe', 39.7, 17.7, 193.0, 3200.0, 'female', 2009),
 (113, 'Adelie', 'Biscoe', 42.2, 19.5, 197.0, 4275.0, 'male', 2009),
 (114, 'Adelie', 'Biscoe', 39.6, 20.7, 191.0, 3900.0, 'female', 2009),
 (115, 'Adelie', 'Biscoe', 42.7, 18.3, 196.0, 4075.0, 'male', 2009),
 (116, 'Adelie', 'Torgersen', 38.6, 17.0, 188.0, 2900.0, 'female', 2009),
 (117, 'Adelie', 'Torgersen', 37.3, 20.5, 199.0, 3775.0, 'male', 2009),
 (118, 'Adelie', 'Torgersen', 35.7, 17.0, 189.0, 3350.0, 'female', 2009),
 (119, 'Adelie', 'Torgersen', 41.1, 18.6, 189.0, 3325.0, 'male', 2009),
 (120, 'Adelie', 'Torgersen', 36.2, 17.2, 187.0, 3150.0, 'female', 2009),
 (121, 'Adelie', 'Torgersen', 37.7, 19.8, 198.0, 3500.0, 'male', 2009),
 (122, 'Adelie', 'Torgersen', 40.2, 17.0, 176.0, 3450.0, 'female', 2009),
 (123, 'Adelie', 'Torgersen', 41.4, 18.5, 202.0, 3875.0, 'male', 2009),
 (124, 'Adelie', 'Torgersen', 35.2, 15.9, 186.0, 3050.0, 'female', 2009),
 (125, 'Adelie', 'Torgersen', 40.6, 19.0, 199.0, 4000.0, 'male', 2009),
 (126, 'Adelie', 'Torgersen', 38.8, 17.6, 191.0, 3275.0, 'female', 2009),
 (127, 'Adelie', 'Torgersen', 41.5, 18.3, 195.0, 4300.0, 'male', 2009),
 (128, 'Adelie', 'Torgersen', 39.0, 17.1, 191.0, 3050.0, 'female', 2009),
 (129, 'Adelie', 'Torgersen', 44.1, 18.0, 210.0, 4000.0, 'male', 2009),
 (130, 'Adelie', 'Torgersen', 38.5, 17.9, 190.0, 3325.0, 'female', 2009),
 (131, 'Adelie', 'Torgersen', 43.1, 19.2, 197.0, 3500.0, 'male', 2009),
 (132, 'Adelie', 'Dream', 36.8, 18.5, 193.0, 3500.0, 'female', 2009),
 (133, 'Adelie', 'Dream', 37.5, 18.5, 199.0, 4475.0, 'male', 2009),
 (134, 'Adelie', 'Dream', 38.1, 17.6, 187.0, 3425.0, 'female', 2009),
 (135, 'Adelie', 'Dream', 41.1, 17.5, 190.0, 3900.0, 'male', 2009),
 (136, 'Adelie', 'Dream', 35.6, 17.5, 191.0, 3175.0, 'female', 2009),
 (137, 'Adelie', 'Dream', 40.2, 20.1, 200.0, 3975.0, 'male', 2009),
 (138, 'Adelie', 'Dream', 37.0, 16.5, 185.0, 3400.0, 'female', 2009),
 (139, 'Adelie', 'Dream', 39.7, 17.9, 193.0, 4250.0, 'male', 2009),
 (140, 'Adelie', 'Dream', 40.2, 17.1, 193.0, 3400.0, 'female', 2009),
 (141, 'Adelie', 'Dream', 40.6, 17.2, 187.0, 3475.0, 'male', 2009),
 (142, 'Adelie', 'Dream', 32.1, 15.5, 188.0, 3050.0, 'female', 2009),
 (143, 'Adelie', 'Dream', 40.7, 17.0, 190.0, 3725.0, 'male', 2009),
 (144, 'Adelie', 'Dream', 37.3, 16.8, 192.0, 3000.0, 'female', 2009),
 (145, 'Adelie', 'Dream', 39.0, 18.7, 185.0, 3650.0, 'male', 2009),
 (146, 'Adelie', 'Dream', 39.2, 18.6, 190.0, 4250.0, 'male', 2009),
 (147, 'Adelie', 'Dream', 36.6, 18.4, 184.0, 3475.0, 'female', 2009),
 (148, 'Adelie', 'Dream', 36.0, 17.8, 195.0, 3450.0, 'female', 2009),
 (149, 'Adelie', 'Dream', 37.8, 18.1, 193.0, 3750.0, 'male', 2009),
 (150, 'Adelie', 'Dream', 36.0, 17.1, 187.0, 3700.0, 'female', 2009),
 (151, 'Adelie', 'Dream', 41.5, 18.5, 201.0, 4000.0, 'male', 2009)]

In [29]:
%%sql
SELECT *
FROM palmer
WHERE NOT species='Adelie';

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(152, 'Gentoo', 'Biscoe', 46.1, 13.2, 211.0, 4500.0, 'female', 2007),
 (153, 'Gentoo', 'Biscoe', 50.0, 16.3, 230.0, 5700.0, 'male', 2007),
 (154, 'Gentoo', 'Biscoe', 48.7, 14.1, 210.0, 4450.0, 'female', 2007),
 (155, 'Gentoo', 'Biscoe', 50.0, 15.2, 218.0, 5700.0, 'male', 2007),
 (156, 'Gentoo', 'Biscoe', 47.6, 14.5, 215.0, 5400.0, 'male', 2007),
 (157, 'Gentoo', 'Biscoe', 46.5, 13.5, 210.0, 4550.0, 'female', 2007),
 (158, 'Gentoo', 'Biscoe', 45.4, 14.6, 211.0, 4800.0, 'female', 2007),
 (159, 'Gentoo', 'Biscoe', 46.7, 15.3, 219.0, 5200.0, 'male', 2007),
 (160, 'Gentoo', 'Biscoe', 43.3, 13.4, 209.0, 4400.0, 'female', 2007),
 (161, 'Gentoo', 'Biscoe', 46.8, 15.4, 215.0, 5150.0, 'male', 2007),
 (162, 'Gentoo', 'Biscoe', 40.9, 13.7, 214.0, 4650.0, 'female', 2007),
 (163, 'Gentoo', 'Biscoe', 49.0, 16.1, 216.0, 5550.0, 'male', 2007),
 (164, 'Gentoo', 'Biscoe', 45.5, 13.7, 214.0, 4650.0, 'female', 2007),
 (165, 'Gentoo', 'Biscoe', 48.4, 14.6, 213.0, 5850.0, 'male', 2007),
 (166, 'Gentoo', 'Biscoe', 45.8, 14.6, 210.0, 4200.0, 'female', 2007),
 (167, 'Gentoo', 'Biscoe', 49.3, 15.7, 217.0, 5850.0, 'male', 2007),
 (168, 'Gentoo', 'Biscoe', 42.0, 13.5, 210.0, 4150.0, 'female', 2007),
 (169, 'Gentoo', 'Biscoe', 49.2, 15.2, 221.0, 6300.0, 'male', 2007),
 (170, 'Gentoo', 'Biscoe', 46.2, 14.5, 209.0, 4800.0, 'female', 2007),
 (171, 'Gentoo', 'Biscoe', 48.7, 15.1, 222.0, 5350.0, 'male', 2007),
 (172, 'Gentoo', 'Biscoe', 50.2, 14.3, 218.0, 5700.0, 'male', 2007),
 (173, 'Gentoo', 'Biscoe', 45.1, 14.5, 215.0, 5000.0, 'female', 2007),
 (174, 'Gentoo', 'Biscoe', 46.5, 14.5, 213.0, 4400.0, 'female', 2007),
 (175, 'Gentoo', 'Biscoe', 46.3, 15.8, 215.0, 5050.0, 'male', 2007),
 (176, 'Gentoo', 'Biscoe', 42.9, 13.1, 215.0, 5000.0, 'female', 2007),
 (177, 'Gentoo', 'Biscoe', 46.1, 15.1, 215.0, 5100.0, 'male', 2007),
 (178, 'Gentoo', 'Biscoe', 44.5, 14.3, 216.0, 4100.0, None, 2007),
 (179, 'Gentoo', 'Biscoe', 47.8, 15.0, 215.0, 5650.0, 'male', 2007),
 (180, 'Gentoo', 'Biscoe', 48.2, 14.3, 210.0, 4600.0, 'female', 2007),
 (181, 'Gentoo', 'Biscoe', 50.0, 15.3, 220.0, 5550.0, 'male', 2007),
 (182, 'Gentoo', 'Biscoe', 47.3, 15.3, 222.0, 5250.0, 'male', 2007),
 (183, 'Gentoo', 'Biscoe', 42.8, 14.2, 209.0, 4700.0, 'female', 2007),
 (184, 'Gentoo', 'Biscoe', 45.1, 14.5, 207.0, 5050.0, 'female', 2007),
 (185, 'Gentoo', 'Biscoe', 59.6, 17.0, 230.0, 6050.0, 'male', 2007),
 (186, 'Gentoo', 'Biscoe', 49.1, 14.8, 220.0, 5150.0, 'female', 2008),
 (187, 'Gentoo', 'Biscoe', 48.4, 16.3, 220.0, 5400.0, 'male', 2008),
 (188, 'Gentoo', 'Biscoe', 42.6, 13.7, 213.0, 4950.0, 'female', 2008),
 (189, 'Gentoo', 'Biscoe', 44.4, 17.3, 219.0, 5250.0, 'male', 2008),
 (190, 'Gentoo', 'Biscoe', 44.0, 13.6, 208.0, 4350.0, 'female', 2008),
 (191, 'Gentoo', 'Biscoe', 48.7, 15.7, 208.0, 5350.0, 'male', 2008),
 (192, 'Gentoo', 'Biscoe', 42.7, 13.7, 208.0, 3950.0, 'female', 2008),
 (193, 'Gentoo', 'Biscoe', 49.6, 16.0, 225.0, 5700.0, 'male', 2008),
 (194, 'Gentoo', 'Biscoe', 45.3, 13.7, 210.0, 4300.0, 'female', 2008),
 (195, 'Gentoo', 'Biscoe', 49.6, 15.0, 216.0, 4750.0, 'male', 2008),
 (196, 'Gentoo', 'Biscoe', 50.5, 15.9, 222.0, 5550.0, 'male', 2008),
 (197, 'Gentoo', 'Biscoe', 43.6, 13.9, 217.0, 4900.0, 'female', 2008),
 (198, 'Gentoo', 'Biscoe', 45.5, 13.9, 210.0, 4200.0, 'female', 2008),
 (199, 'Gentoo', 'Biscoe', 50.5, 15.9, 225.0, 5400.0, 'male', 2008),
 (200, 'Gentoo', 'Biscoe', 44.9, 13.3, 213.0, 5100.0, 'female', 2008),
 (201, 'Gentoo', 'Biscoe', 45.2, 15.8, 215.0, 5300.0, 'male', 2008),
 (202, 'Gentoo', 'Biscoe', 46.6, 14.2, 210.0, 4850.0, 'female', 2008),
 (203, 'Gentoo', 'Biscoe', 48.5, 14.1, 220.0, 5300.0, 'male', 2008),
 (204, 'Gentoo', 'Biscoe', 45.1, 14.4, 210.0, 4400.0, 'female', 2008),
 (205, 'Gentoo', 'Biscoe', 50.1, 15.0, 225.0, 5000.0, 'male', 2008),
 (206, 'Gentoo', 'Biscoe', 46.5, 14.4, 217.0, 4900.0, 'female', 2008),
 (207, 'Gentoo', 'Biscoe', 45.0, 15.4, 220.0, 5050.0, 'male', 2008),
 (208, 'Gentoo', 'Biscoe', 43.8, 13.9, 208.0, 4300.0, 'female', 2008),
 (209, 'Gentoo', 'Biscoe', 45.5, 15.0, 220.0, 5000.0, 'male', 2008),
 (210, 'Gentoo', 'Biscoe', 43.2, 14.5, 208.0, 4450.0, 'female', 2008),
 (211, 'Gentoo', 'Biscoe', 50.4, 15.3, 224.0, 5550.0, 'male', 2008),
 (212, 'Gentoo', 'Biscoe', 45.3, 13.8, 208.0, 4200.0, 'female', 2008),
 (213, 'Gentoo', 'Biscoe', 46.2, 14.9, 221.0, 5300.0, 'male', 2008),
 (214, 'Gentoo', 'Biscoe', 45.7, 13.9, 214.0, 4400.0, 'female', 2008),
 (215, 'Gentoo', 'Biscoe', 54.3, 15.7, 231.0, 5650.0, 'male', 2008),
 (216, 'Gentoo', 'Biscoe', 45.8, 14.2, 219.0, 4700.0, 'female', 2008),
 (217, 'Gentoo', 'Biscoe', 49.8, 16.8, 230.0, 5700.0, 'male', 2008),
 (218, 'Gentoo', 'Biscoe', 46.2, 14.4, 214.0, 4650.0, None, 2008),
 (219, 'Gentoo', 'Biscoe', 49.5, 16.2, 229.0, 5800.0, 'male', 2008),
 (220, 'Gentoo', 'Biscoe', 43.5, 14.2, 220.0, 4700.0, 'female', 2008),
 (221, 'Gentoo', 'Biscoe', 50.7, 15.0, 223.0, 5550.0, 'male', 2008),
 (222, 'Gentoo', 'Biscoe', 47.7, 15.0, 216.0, 4750.0, 'female', 2008),
 (223, 'Gentoo', 'Biscoe', 46.4, 15.6, 221.0, 5000.0, 'male', 2008),
 (224, 'Gentoo', 'Biscoe', 48.2, 15.6, 221.0, 5100.0, 'male', 2008),
 (225, 'Gentoo', 'Biscoe', 46.5, 14.8, 217.0, 5200.0, 'female', 2008),
 (226, 'Gentoo', 'Biscoe', 46.4, 15.0, 216.0, 4700.0, 'female', 2008),
 (227, 'Gentoo', 'Biscoe', 48.6, 16.0, 230.0, 5800.0, 'male', 2008),
 (228, 'Gentoo', 'Biscoe', 47.5, 14.2, 209.0, 4600.0, 'female', 2008),
 (229, 'Gentoo', 'Biscoe', 51.1, 16.3, 220.0, 6000.0, 'male', 2008),
 (230, 'Gentoo', 'Biscoe', 45.2, 13.8, 215.0, 4750.0, 'female', 2008),
 (231, 'Gentoo', 'Biscoe', 45.2, 16.4, 223.0, 5950.0, 'male', 2008),
 (232, 'Gentoo', 'Biscoe', 49.1, 14.5, 212.0, 4625.0, 'female', 2009),
 (233, 'Gentoo', 'Biscoe', 52.5, 15.6, 221.0, 5450.0, 'male', 2009),
 (234, 'Gentoo', 'Biscoe', 47.4, 14.6, 212.0, 4725.0, 'female', 2009),
 (235, 'Gentoo', 'Biscoe', 50.0, 15.9, 224.0, 5350.0, 'male', 2009),
 (236, 'Gentoo', 'Biscoe', 44.9, 13.8, 212.0, 4750.0, 'female', 2009),
 (237, 'Gentoo', 'Biscoe', 50.8, 17.3, 228.0, 5600.0, 'male', 2009),
 (238, 'Gentoo', 'Biscoe', 43.4, 14.4, 218.0, 4600.0, 'female', 2009),
 (239, 'Gentoo', 'Biscoe', 51.3, 14.2, 218.0, 5300.0, 'male', 2009),
 (240, 'Gentoo', 'Biscoe', 47.5, 14.0, 212.0, 4875.0, 'female', 2009),
 (241, 'Gentoo', 'Biscoe', 52.1, 17.0, 230.0, 5550.0, 'male', 2009),
 (242, 'Gentoo', 'Biscoe', 47.5, 15.0, 218.0, 4950.0, 'female', 2009),
 (243, 'Gentoo', 'Biscoe', 52.2, 17.1, 228.0, 5400.0, 'male', 2009),
 (244, 'Gentoo', 'Biscoe', 45.5, 14.5, 212.0, 4750.0, 'female', 2009),
 (245, 'Gentoo', 'Biscoe', 49.5, 16.1, 224.0, 5650.0, 'male', 2009),
 (246, 'Gentoo', 'Biscoe', 44.5, 14.7, 214.0, 4850.0, 'female', 2009),
 (247, 'Gentoo', 'Biscoe', 50.8, 15.7, 226.0, 5200.0, 'male', 2009),
 (248, 'Gentoo', 'Biscoe', 49.4, 15.8, 216.0, 4925.0, 'male', 2009),
 (249, 'Gentoo', 'Biscoe', 46.9, 14.6, 222.0, 4875.0, 'female', 2009),
 (250, 'Gentoo', 'Biscoe', 48.4, 14.4, 203.0, 4625.0, 'female', 2009),
 (251, 'Gentoo', 'Biscoe', 51.1, 16.5, 225.0, 5250.0, 'male', 2009),
 (252, 'Gentoo', 'Biscoe', 48.5, 15.0, 219.0, 4850.0, 'female', 2009),
 (253, 'Gentoo', 'Biscoe', 55.9, 17.0, 228.0, 5600.0, 'male', 2009),
 (254, 'Gentoo', 'Biscoe', 47.2, 15.5, 215.0, 4975.0, 'female', 2009),
 (255, 'Gentoo', 'Biscoe', 49.1, 15.0, 228.0, 5500.0, 'male', 2009),
 (256, 'Gentoo', 'Biscoe', 47.3, 13.8, 216.0, 4725.0, None, 2009),
 (257, 'Gentoo', 'Biscoe', 46.8, 16.1, 215.0, 5500.0, 'male', 2009),
 (258, 'Gentoo', 'Biscoe', 41.7, 14.7, 210.0, 4700.0, 'female', 2009),
 (259, 'Gentoo', 'Biscoe', 53.4, 15.8, 219.0, 5500.0, 'male', 2009),
 (260, 'Gentoo', 'Biscoe', 43.3, 14.0, 208.0, 4575.0, 'female', 2009),
 (261, 'Gentoo', 'Biscoe', 48.1, 15.1, 209.0, 5500.0, 'male', 2009),
 (262, 'Gentoo', 'Biscoe', 50.5, 15.2, 216.0, 5000.0, 'female', 2009),
 (263, 'Gentoo', 'Biscoe', 49.8, 15.9, 229.0, 5950.0, 'male', 2009),
 (264, 'Gentoo', 'Biscoe', 43.5, 15.2, 213.0, 4650.0, 'female', 2009),
 (265, 'Gentoo', 'Biscoe', 51.5, 16.3, 230.0, 5500.0, 'male', 2009),
 (266, 'Gentoo', 'Biscoe', 46.2, 14.1, 217.0, 4375.0, 'female', 2009),
 (267, 'Gentoo', 'Biscoe', 55.1, 16.0, 230.0, 5850.0, 'male', 2009),
 (268, 'Gentoo', 'Biscoe', 44.5, 15.7, 217.0, 4875.0, None, 2009),
 (269, 'Gentoo', 'Biscoe', 48.8, 16.2, 222.0, 6000.0, 'male', 2009),
 (270, 'Gentoo', 'Biscoe', 47.2, 13.7, 214.0, 4925.0, 'female', 2009),
 (271, 'Gentoo', 'Biscoe', None, None, None, None, None, 2009),
 (272, 'Gentoo', 'Biscoe', 46.8, 14.3, 215.0, 4850.0, 'female', 2009),
 (273, 'Gentoo', 'Biscoe', 50.4, 15.7, 222.0, 5750.0, 'male', 2009),
 (274, 'Gentoo', 'Biscoe', 45.2, 14.8, 212.0, 5200.0, 'female', 2009),
 (275, 'Gentoo', 'Biscoe', 49.9, 16.1, 213.0, 5400.0, 'male', 2009),
 (276, 'Chinstrap', 'Dream', 46.5, 17.9, 192.0, 3500.0, 'female', 2007),
 (277, 'Chinstrap', 'Dream', 50.0, 19.5, 196.0, 3900.0, 'male', 2007),
 (278, 'Chinstrap', 'Dream', 51.3, 19.2, 193.0, 3650.0, 'male', 2007),
 (279, 'Chinstrap', 'Dream', 45.4, 18.7, 188.0, 3525.0, 'female', 2007),
 (280, 'Chinstrap', 'Dream', 52.7, 19.8, 197.0, 3725.0, 'male', 2007),
 (281, 'Chinstrap', 'Dream', 45.2, 17.8, 198.0, 3950.0, 'female', 2007),
 (282, 'Chinstrap', 'Dream', 46.1, 18.2, 178.0, 3250.0, 'female', 2007),
 (283, 'Chinstrap', 'Dream', 51.3, 18.2, 197.0, 3750.0, 'male', 2007),
 (284, 'Chinstrap', 'Dream', 46.0, 18.9, 195.0, 4150.0, 'female', 2007),
 (285, 'Chinstrap', 'Dream', 51.3, 19.9, 198.0, 3700.0, 'male', 2007),
 (286, 'Chinstrap', 'Dream', 46.6, 17.8, 193.0, 3800.0, 'female', 2007),
 (287, 'Chinstrap', 'Dream', 51.7, 20.3, 194.0, 3775.0, 'male', 2007),
 (288, 'Chinstrap', 'Dream', 47.0, 17.3, 185.0, 3700.0, 'female', 2007),
 (289, 'Chinstrap', 'Dream', 52.0, 18.1, 201.0, 4050.0, 'male', 2007),
 (290, 'Chinstrap', 'Dream', 45.9, 17.1, 190.0, 3575.0, 'female', 2007),
 (291, 'Chinstrap', 'Dream', 50.5, 19.6, 201.0, 4050.0, 'male', 2007),
 (292, 'Chinstrap', 'Dream', 50.3, 20.0, 197.0, 3300.0, 'male', 2007),
 (293, 'Chinstrap', 'Dream', 58.0, 17.8, 181.0, 3700.0, 'female', 2007),
 (294, 'Chinstrap', 'Dream', 46.4, 18.6, 190.0, 3450.0, 'female', 2007),
 (295, 'Chinstrap', 'Dream', 49.2, 18.2, 195.0, 4400.0, 'male', 2007),
 (296, 'Chinstrap', 'Dream', 42.4, 17.3, 181.0, 3600.0, 'female', 2007),
 (297, 'Chinstrap', 'Dream', 48.5, 17.5, 191.0, 3400.0, 'male', 2007),
 (298, 'Chinstrap', 'Dream', 43.2, 16.6, 187.0, 2900.0, 'female', 2007),
 (299, 'Chinstrap', 'Dream', 50.6, 19.4, 193.0, 3800.0, 'male', 2007),
 (300, 'Chinstrap', 'Dream', 46.7, 17.9, 195.0, 3300.0, 'female', 2007),
 (301, 'Chinstrap', 'Dream', 52.0, 19.0, 197.0, 4150.0, 'male', 2007),
 (302, 'Chinstrap', 'Dream', 50.5, 18.4, 200.0, 3400.0, 'female', 2008),
 (303, 'Chinstrap', 'Dream', 49.5, 19.0, 200.0, 3800.0, 'male', 2008),
 (304, 'Chinstrap', 'Dream', 46.4, 17.8, 191.0, 3700.0, 'female', 2008),
 (305, 'Chinstrap', 'Dream', 52.8, 20.0, 205.0, 4550.0, 'male', 2008),
 (306, 'Chinstrap', 'Dream', 40.9, 16.6, 187.0, 3200.0, 'female', 2008),
 (307, 'Chinstrap', 'Dream', 54.2, 20.8, 201.0, 4300.0, 'male', 2008),
 (308, 'Chinstrap', 'Dream', 42.5, 16.7, 187.0, 3350.0, 'female', 2008),
 (309, 'Chinstrap', 'Dream', 51.0, 18.8, 203.0, 4100.0, 'male', 2008),
 (310, 'Chinstrap', 'Dream', 49.7, 18.6, 195.0, 3600.0, 'male', 2008),
 (311, 'Chinstrap', 'Dream', 47.5, 16.8, 199.0, 3900.0, 'female', 2008),
 (312, 'Chinstrap', 'Dream', 47.6, 18.3, 195.0, 3850.0, 'female', 2008),
 (313, 'Chinstrap', 'Dream', 52.0, 20.7, 210.0, 4800.0, 'male', 2008),
 (314, 'Chinstrap', 'Dream', 46.9, 16.6, 192.0, 2700.0, 'female', 2008),
 (315, 'Chinstrap', 'Dream', 53.5, 19.9, 205.0, 4500.0, 'male', 2008),
 (316, 'Chinstrap', 'Dream', 49.0, 19.5, 210.0, 3950.0, 'male', 2008),
 (317, 'Chinstrap', 'Dream', 46.2, 17.5, 187.0, 3650.0, 'female', 2008),
 (318, 'Chinstrap', 'Dream', 50.9, 19.1, 196.0, 3550.0, 'male', 2008),
 (319, 'Chinstrap', 'Dream', 45.5, 17.0, 196.0, 3500.0, 'female', 2008),
 (320, 'Chinstrap', 'Dream', 50.9, 17.9, 196.0, 3675.0, 'female', 2009),
 (321, 'Chinstrap', 'Dream', 50.8, 18.5, 201.0, 4450.0, 'male', 2009),
 (322, 'Chinstrap', 'Dream', 50.1, 17.9, 190.0, 3400.0, 'female', 2009),
 (323, 'Chinstrap', 'Dream', 49.0, 19.6, 212.0, 4300.0, 'male', 2009),
 (324, 'Chinstrap', 'Dream', 51.5, 18.7, 187.0, 3250.0, 'male', 2009),
 (325, 'Chinstrap', 'Dream', 49.8, 17.3, 198.0, 3675.0, 'female', 2009),
 (326, 'Chinstrap', 'Dream', 48.1, 16.4, 199.0, 3325.0, 'female', 2009),
 (327, 'Chinstrap', 'Dream', 51.4, 19.0, 201.0, 3950.0, 'male', 2009),
 (328, 'Chinstrap', 'Dream', 45.7, 17.3, 193.0, 3600.0, 'female', 2009),
 (329, 'Chinstrap', 'Dream', 50.7, 19.7, 203.0, 4050.0, 'male', 2009),
 (330, 'Chinstrap', 'Dream', 42.5, 17.3, 187.0, 3350.0, 'female', 2009),
 (331, 'Chinstrap', 'Dream', 52.2, 18.8, 197.0, 3450.0, 'male', 2009),
 (332, 'Chinstrap', 'Dream', 45.2, 16.6, 191.0, 3250.0, 'female', 2009),
 (333, 'Chinstrap', 'Dream', 49.3, 19.9, 203.0, 4050.0, 'male', 2009),
 (334, 'Chinstrap', 'Dream', 50.2, 18.8, 202.0, 3800.0, 'male', 2009),
 (335, 'Chinstrap', 'Dream', 45.6, 19.4, 194.0, 3525.0, 'female', 2009),
 (336, 'Chinstrap', 'Dream', 51.9, 19.5, 206.0, 3950.0, 'male', 2009),
 (337, 'Chinstrap', 'Dream', 46.8, 16.5, 189.0, 3650.0, 'female', 2009),
 (338, 'Chinstrap', 'Dream', 45.7, 17.0, 195.0, 3650.0, 'female', 2009),
 (339, 'Chinstrap', 'Dream', 55.8, 19.8, 207.0, 4000.0, 'male', 2009),
 (340, 'Chinstrap', 'Dream', 43.5, 18.1, 202.0, 3400.0, 'female', 2009),
 (341, 'Chinstrap', 'Dream', 49.6, 18.2, 193.0, 3775.0, 'male', 2009),
 (342, 'Chinstrap', 'Dream', 50.8, 19.0, 210.0, 4100.0, 'male', 2009),
 (343, 'Chinstrap', 'Dream', 50.2, 18.7, 198.0, 3775.0, 'female', 2009)]

In [31]:
%%sql
SELECT *
FROM palmer
WHERE species IS NULL;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[]

In [33]:
%%sql
SELECT *
FROM palmer
WHERE species IS NOT NULL
LIMIT 3;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(0, 'Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'male', 2007),
 (1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (2, 'Adelie', 'Torgersen', 40.3, 18.0, 195.0, 3250.0, 'female', 2007)]

In [36]:
%%sql
SELECT * FROM palmer
WHERE bill_length_mm='39.1'
OR bill_length_mm='39.5'
OR bill_length_mm='40.5';

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(0, 'Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'male', 2007),
 (1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (27, 'Adelie', 'Biscoe', 40.5, 17.9, 187.0, 3200.0, 'female', 2007),
 (29, 'Adelie', 'Biscoe', 40.5, 18.9, 180.0, 3950.0, 'male', 2007),
 (30, 'Adelie', 'Dream', 39.5, 16.7, 178.0, 3250.0, 'female', 2007),
 (32, 'Adelie', 'Dream', 39.5, 17.8, 188.0, 3300.0, 'female', 2007)]

In [37]:
%%sql
SELECT * FROM palmer
ORDER BY bill_length_mm
LIMIT 7;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(3, 'Adelie', 'Torgersen', None, None, None, None, None, 2007),
 (271, 'Gentoo', 'Biscoe', None, None, None, None, None, 2009),
 (142, 'Adelie', 'Dream', 32.1, 15.5, 188.0, 3050.0, 'female', 2009),
 (98, 'Adelie', 'Dream', 33.1, 16.1, 178.0, 2900.0, 'female', 2008),
 (70, 'Adelie', 'Torgersen', 33.5, 19.0, 190.0, 3600.0, 'female', 2008),
 (92, 'Adelie', 'Dream', 34.0, 17.1, 185.0, 3400.0, 'female', 2008),
 (8, 'Adelie', 'Torgersen', 34.1, 18.1, 193.0, 3475.0, None, 2007)]

In [38]:
%%sql
SELECT * FROM palmer
WHERE bill_length_mm IS NULL;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(3, 'Adelie', 'Torgersen', None, None, None, None, None, 2007),
 (271, 'Gentoo', 'Biscoe', None, None, None, None, None, 2009)]

In [40]:
%%sql
SELECT * FROM palmer
WHERE species='Adelie'
ORDER BY bill_length_mm DESC
LIMIT 5;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(19, 'Adelie', 'Torgersen', 46.0, 21.5, 194.0, 4200.0, 'male', 2007),
 (73, 'Adelie', 'Torgersen', 45.8, 18.9, 197.0, 4150.0, 'male', 2008),
 (111, 'Adelie', 'Biscoe', 45.6, 20.3, 191.0, 4600.0, 'male', 2009),
 (43, 'Adelie', 'Dream', 44.1, 19.7, 196.0, 4400.0, 'male', 2007),
 (129, 'Adelie', 'Torgersen', 44.1, 18.0, 210.0, 4000.0, 'male', 2009)]

ASC:昇順、DESC:降順

In [41]:
%%sql
SELECT DISTINCT(bill_length_mm)
FROM palmer;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(39.1,),
 (39.5,),
 (40.3,),
 (None,),
 (36.7,),
 (39.3,),
 (38.9,),
 (39.2,),
 (34.1,),
 (42.0,),
 (37.8,),
 (41.1,),
 (38.6,),
 (34.6,),
 (36.6,),
 (38.7,),
 (42.5,),
 (34.4,),
 (46.0,),
 (37.7,),
 (35.9,),
 (38.2,),
 (38.8,),
 (35.3,),
 (40.6,),
 (40.5,),
 (37.9,),
 (37.2,),
 (40.9,),
 (36.4,),
 (42.2,),
 (37.6,),
 (39.8,),
 (36.5,),
 (40.8,),
 (36.0,),
 (44.1,),
 (37.0,),
 (39.6,),
 (37.5,),
 (42.3,),
 (40.1,),
 (35.0,),
 (34.5,),
 (41.4,),
 (39.0,),
 (35.7,),
 (41.3,),
 (41.6,),
 (35.5,),
 (41.8,),
 (33.5,),
 (39.7,),
 (45.8,),
 (42.8,),
 (36.2,),
 (42.1,),
 (42.9,),
 (35.1,),
 (37.3,),
 (36.3,),
 (36.9,),
 (38.3,),
 (34.0,),
 (38.1,),
 (33.1,),
 (43.2,),
 (41.0,),
 (45.6,),
 (42.7,),
 (40.2,),
 (35.2,),
 (41.5,),
 (38.5,),
 (43.1,),
 (36.8,),
 (35.6,),
 (32.1,),
 (40.7,),
 (46.1,),
 (50.0,),
 (48.7,),
 (47.6,),
 (46.5,),
 (45.4,),
 (46.7,),
 (43.3,),
 (46.8,),
 (49.0,),
 (45.5,),
 (48.4,),
 (49.3,),
 (49.2,),
 (46.2,),
 (50.2,),
 (45.1,),
 (46.3,),
 (44.5,),
 (47.8,),
 (48.2,),
 (47.3,),
 (59.6,),
 (49.1,),
 (42.6,),
 (44.4,),
 (44.0,),
 (49.6,),
 (45.3,),
 (50.5,),
 (43.6,),
 (44.9,),
 (45.2,),
 (46.6,),
 (48.5,),
 (50.1,),
 (45.0,),
 (43.8,),
 (50.4,),
 (45.7,),
 (54.3,),
 (49.8,),
 (49.5,),
 (43.5,),
 (50.7,),
 (47.7,),
 (46.4,),
 (48.6,),
 (47.5,),
 (51.1,),
 (52.5,),
 (47.4,),
 (50.8,),
 (43.4,),
 (51.3,),
 (52.1,),
 (52.2,),
 (49.4,),
 (46.9,),
 (55.9,),
 (47.2,),
 (41.7,),
 (53.4,),
 (48.1,),
 (51.5,),
 (55.1,),
 (48.8,),
 (49.9,),
 (52.7,),
 (51.7,),
 (47.0,),
 (52.0,),
 (45.9,),
 (50.3,),
 (58.0,),
 (42.4,),
 (50.6,),
 (52.8,),
 (54.2,),
 (51.0,),
 (49.7,),
 (53.5,),
 (50.9,),
 (51.4,),
 (51.9,),
 (55.8,)]

In [42]:
%%sql
SELECT * FROM palmer
WHERE bill_length_mm=39.5;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (30, 'Adelie', 'Dream', 39.5, 16.7, 178.0, 3250.0, 'female', 2007),
 (32, 'Adelie', 'Dream', 39.5, 17.8, 188.0, 3300.0, 'female', 2007)]

In [43]:
%%sql
SELECT sum(bill_length_mm)
FROM palmer;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(15021.300000000007,)]

In [44]:
%%sql
SELECT AVG(bill_length_mm)
FROM palmer
WHERE species='Adelie';

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(38.79139072847684,)]

In [45]:
%%sql
SELECT AVG(bill_length_mm)
FROM palmer

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(43.921929824561424,)]

In [47]:
%%sql
SELECT COUNT(species)
FROM palmer;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(344,)]

In [48]:
%%sql
SELECT COUNT(*)
FROM palmer;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(344,)]

In [50]:
%%sql
SELECT species,MIN(bill_length_mm)
FROM palmer;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[('Adelie', 32.1)]

In [53]:
%%sql
SELECT SUM(bill_length_mm),species
FROM palmer
GROUP BY species;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(5857.500000000003, 'Adelie'),
 (3320.7000000000003, 'Chinstrap'),
 (5843.0999999999985, 'Gentoo')]

In [55]:
%%sql
SELECT SUM(bill_length_mm),species
FROM palmer
GROUP BY species
HAVING SUM(bill_length_mm)>40;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(5857.500000000003, 'Adelie'),
 (3320.7000000000003, 'Chinstrap'),
 (5843.0999999999985, 'Gentoo')]

HAVINGはGROUP BYによってグループ化されたデータを検索対象とする。

In [57]:
%%sql
INSERT INTO palmer
VALUES('ペンギン','ペンギン','ペンギン','ペンギン','ペンギン','pe','pe','pe','pe');

   sqlite:///chinook.db
 * sqlite:///penguins.db
1 rows affected.

[]

In [58]:
%%sql
SELECT *
FROM palmer
WHERE species='ペンギン';

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[('ペンギン', 'ペンギン', 'ペンギン', 'ペンギン', 'ペンギン', 'pe', 'pe', 'pe', 'pe')]

In [63]:
%%sql
UPDATE palmer
SET bill_length_mm=40.0
WHERE island='ペンギン';

   sqlite:///chinook.db
 * sqlite:///penguins.db
1 rows affected.

[]

In [65]:
%%sql
DELETE FROM palmer
WHERE species='ペンギン';

   sqlite:///chinook.db
 * sqlite:///penguins.db
1 rows affected.

[]

In [66]:
%%sql
SELECT * FROM palmer
WHERE species='ペンギン';

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[]

In [69]:
%%sql
SELECT *
FROM palmer
WHERE bill_length_mm BETWEEN 35 AND 39;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(4, 'Adelie', 'Torgersen', 36.7, 19.3, 193.0, 3450.0, 'female', 2007),
 (6, 'Adelie', 'Torgersen', 38.9, 17.8, 181.0, 3625.0, 'female', 2007),
 (10, 'Adelie', 'Torgersen', 37.8, 17.1, 186.0, 3300.0, None, 2007),
 (11, 'Adelie', 'Torgersen', 37.8, 17.3, 180.0, 3700.0, None, 2007),
 (13, 'Adelie', 'Torgersen', 38.6, 21.2, 191.0, 3800.0, 'male', 2007),
 (15, 'Adelie', 'Torgersen', 36.6, 17.8, 185.0, 3700.0, 'female', 2007),
 (16, 'Adelie', 'Torgersen', 38.7, 19.0, 195.0, 3450.0, 'female', 2007),
 (20, 'Adelie', 'Biscoe', 37.8, 18.3, 174.0, 3400.0, 'female', 2007),
 (21, 'Adelie', 'Biscoe', 37.7, 18.7, 180.0, 3600.0, 'male', 2007),
 (22, 'Adelie', 'Biscoe', 35.9, 19.2, 189.0, 3800.0, 'female', 2007),
 (23, 'Adelie', 'Biscoe', 38.2, 18.1, 185.0, 3950.0, 'male', 2007),
 (24, 'Adelie', 'Biscoe', 38.8, 17.2, 180.0, 3800.0, 'male', 2007),
 (25, 'Adelie', 'Biscoe', 35.3, 18.9, 187.0, 3800.0, 'female', 2007),
 (28, 'Adelie', 'Biscoe', 37.9, 18.6, 172.0, 3150.0, 'female', 2007),
 (31, 'Adelie', 'Dream', 37.2, 18.1, 178.0, 3900.0, 'male', 2007),
 (34, 'Adelie', 'Dream', 36.4, 17.0, 195.0, 3325.0, 'female', 2007),
 (36, 'Adelie', 'Dream', 38.8, 20.0, 190.0, 3950.0, 'male', 2007),
 (38, 'Adelie', 'Dream', 37.6, 19.3, 181.0, 3300.0, 'female', 2007),
 (40, 'Adelie', 'Dream', 36.5, 18.0, 182.0, 3150.0, 'female', 2007),
 (42, 'Adelie', 'Dream', 36.0, 18.5, 186.0, 3100.0, 'female', 2007),
 (44, 'Adelie', 'Dream', 37.0, 16.9, 185.0, 3000.0, 'female', 2007),
 (47, 'Adelie', 'Dream', 37.5, 18.9, 179.0, 2975.0, None, 2007),
 (48, 'Adelie', 'Dream', 36.0, 17.9, 190.0, 3450.0, 'female', 2007),
 (52, 'Adelie', 'Biscoe', 35.0, 17.9, 190.0, 3450.0, 'female', 2008),
 (56, 'Adelie', 'Biscoe', 39.0, 17.5, 186.0, 3550.0, 'female', 2008),
 (58, 'Adelie', 'Biscoe', 36.5, 16.6, 181.0, 2850.0, 'female', 2008),
 (59, 'Adelie', 'Biscoe', 37.6, 19.1, 194.0, 3750.0, 'male', 2008),
 (60, 'Adelie', 'Biscoe', 35.7, 16.9, 185.0, 3150.0, 'female', 2008),
 (62, 'Adelie', 'Biscoe', 37.6, 17.0, 185.0, 3600.0, 'female', 2008),
 (64, 'Adelie', 'Biscoe', 36.4, 17.1, 184.0, 2850.0, 'female', 2008),
 (66, 'Adelie', 'Biscoe', 35.5, 16.2, 195.0, 3350.0, 'female', 2008),
 (68, 'Adelie', 'Torgersen', 35.9, 16.6, 190.0, 3050.0, 'female', 2008),
 (74, 'Adelie', 'Torgersen', 35.5, 17.5, 190.0, 3700.0, 'female', 2008),
 (77, 'Adelie', 'Torgersen', 37.2, 19.4, 184.0, 3900.0, 'male', 2008),
 (78, 'Adelie', 'Torgersen', 36.2, 16.1, 187.0, 3550.0, 'female', 2008),
 (82, 'Adelie', 'Torgersen', 36.7, 18.8, 187.0, 3800.0, 'female', 2008),
 (83, 'Adelie', 'Torgersen', 35.1, 19.4, 193.0, 4200.0, 'male', 2008),
 (84, 'Adelie', 'Dream', 37.3, 17.8, 191.0, 3350.0, 'female', 2008),
 (86, 'Adelie', 'Dream', 36.3, 19.5, 190.0, 3800.0, 'male', 2008),
 (87, 'Adelie', 'Dream', 36.9, 18.6, 189.0, 3500.0, 'female', 2008),
 (88, 'Adelie', 'Dream', 38.3, 19.2, 189.0, 3950.0, 'male', 2008),
 (89, 'Adelie', 'Dream', 38.9, 18.8, 190.0, 3600.0, 'female', 2008),
 (90, 'Adelie', 'Dream', 35.7, 18.0, 202.0, 3550.0, 'female', 2008),
 (94, 'Adelie', 'Dream', 36.2, 17.3, 187.0, 3300.0, 'female', 2008),
 (96, 'Adelie', 'Dream', 38.1, 18.6, 190.0, 3700.0, 'female', 2008),
 (100, 'Adelie', 'Biscoe', 35.0, 17.9, 192.0, 3725.0, 'female', 2009),
 (102, 'Adelie', 'Biscoe', 37.7, 16.0, 183.0, 3075.0, 'female', 2009),
 (103, 'Adelie', 'Biscoe', 37.8, 20.0, 190.0, 4250.0, 'male', 2009),
 (104, 'Adelie', 'Biscoe', 37.9, 18.6, 193.0, 2925.0, 'female', 2009),
 (106, 'Adelie', 'Biscoe', 38.6, 17.2, 199.0, 3750.0, 'female', 2009),
 (107, 'Adelie', 'Biscoe', 38.2, 20.0, 190.0, 3900.0, 'male', 2009),
 (108, 'Adelie', 'Biscoe', 38.1, 17.0, 181.0, 3175.0, 'female', 2009),
 (110, 'Adelie', 'Biscoe', 38.1, 16.5, 198.0, 3825.0, 'female', 2009),
 (116, 'Adelie', 'Torgersen', 38.6, 17.0, 188.0, 2900.0, 'female', 2009),
 (117, 'Adelie', 'Torgersen', 37.3, 20.5, 199.0, 3775.0, 'male', 2009),
 (118, 'Adelie', 'Torgersen', 35.7, 17.0, 189.0, 3350.0, 'female', 2009),
 (120, 'Adelie', 'Torgersen', 36.2, 17.2, 187.0, 3150.0, 'female', 2009),
 (121, 'Adelie', 'Torgersen', 37.7, 19.8, 198.0, 3500.0, 'male', 2009),
 (124, 'Adelie', 'Torgersen', 35.2, 15.9, 186.0, 3050.0, 'female', 2009),
 (126, 'Adelie', 'Torgersen', 38.8, 17.6, 191.0, 3275.0, 'female', 2009),
 (128, 'Adelie', 'Torgersen', 39.0, 17.1, 191.0, 3050.0, 'female', 2009),
 (130, 'Adelie', 'Torgersen', 38.5, 17.9, 190.0, 3325.0, 'female', 2009),
 (132, 'Adelie', 'Dream', 36.8, 18.5, 193.0, 3500.0, 'female', 2009),
 (133, 'Adelie', 'Dream', 37.5, 18.5, 199.0, 4475.0, 'male', 2009),
 (134, 'Adelie', 'Dream', 38.1, 17.6, 187.0, 3425.0, 'female', 2009),
 (136, 'Adelie', 'Dream', 35.6, 17.5, 191.0, 3175.0, 'female', 2009),
 (138, 'Adelie', 'Dream', 37.0, 16.5, 185.0, 3400.0, 'female', 2009),
 (144, 'Adelie', 'Dream', 37.3, 16.8, 192.0, 3000.0, 'female', 2009),
 (145, 'Adelie', 'Dream', 39.0, 18.7, 185.0, 3650.0, 'male', 2009),
 (147, 'Adelie', 'Dream', 36.6, 18.4, 184.0, 3475.0, 'female', 2009),
 (148, 'Adelie', 'Dream', 36.0, 17.8, 195.0, 3450.0, 'female', 2009),
 (149, 'Adelie', 'Dream', 37.8, 18.1, 193.0, 3750.0, 'male', 2009),
 (150, 'Adelie', 'Dream', 36.0, 17.1, 187.0, 3700.0, 'female', 2009)]

In [70]:
%%sql
SELECT *
FROM palmer
WHERE bill_length_mm IN (39.5, 39.6, 39.7, 39.8);

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(1, 'Adelie', 'Torgersen', 39.5, 17.4, 186.0, 3800.0, 'female', 2007),
 (30, 'Adelie', 'Dream', 39.5, 16.7, 178.0, 3250.0, 'female', 2007),
 (32, 'Adelie', 'Dream', 39.5, 17.8, 188.0, 3300.0, 'female', 2007),
 (39, 'Adelie', 'Dream', 39.8, 19.1, 184.0, 4650.0, 'male', 2007),
 (45, 'Adelie', 'Dream', 39.6, 18.8, 190.0, 4600.0, 'male', 2007),
 (50, 'Adelie', 'Biscoe', 39.6, 17.7, 186.0, 3500.0, 'female', 2008),
 (71, 'Adelie', 'Torgersen', 39.7, 18.4, 190.0, 3900.0, 'male', 2008),
 (72, 'Adelie', 'Torgersen', 39.6, 17.2, 196.0, 3550.0, 'female', 2008),
 (93, 'Adelie', 'Dream', 39.6, 18.1, 186.0, 4450.0, 'male', 2008),
 (105, 'Adelie', 'Biscoe', 39.7, 18.9, 184.0, 3550.0, 'male', 2009),
 (112, 'Adelie', 'Biscoe', 39.7, 17.7, 193.0, 3200.0, 'female', 2009),
 (114, 'Adelie', 'Biscoe', 39.6, 20.7, 191.0, 3900.0, 'female', 2009),
 (139, 'Adelie', 'Dream', 39.7, 17.9, 193.0, 4250.0, 'male', 2009)]

In [73]:
%%sql
SELECT *
FROM palmer
WHERE bill_length_mm =< ANY(39.5, 36.6, 39.7);

   sqlite:///chinook.db
 * sqlite:///penguins.db
(sqlite3.OperationalError) near "<": syntax error
[SQL: SELECT *
FROM palmer
WHERE bill_length_mm =< ANY(39.5, 36.6, 39.7);]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

ANYは引数のいずれかが真なら真、ALLはすべてが真なら真と判定される、はず。ここcolaboではメソッドみつからない。

In [75]:
%%sql
SELECT *
FROM palmer
LIMIT 5 OFFSET 200;

   sqlite:///chinook.db
 * sqlite:///penguins.db
Done.

[(200, 'Gentoo', 'Biscoe', 44.9, 13.3, 213.0, 5100.0, 'female', 2008),
 (201, 'Gentoo', 'Biscoe', 45.2, 15.8, 215.0, 5300.0, 'male', 2008),
 (202, 'Gentoo', 'Biscoe', 46.6, 14.2, 210.0, 4850.0, 'female', 2008),
 (203, 'Gentoo', 'Biscoe', 48.5, 14.1, 220.0, 5300.0, 'male', 2008),
 (204, 'Gentoo', 'Biscoe', 45.1, 14.4, 210.0, 4400.0, 'female', 2008)]